### ISSUE TITLE
Json results

### ISSUE THREAD

**Issue by CGreen4u** [maliceio/malice-sophos#1]
hi, i'm attempting to run my own documents through the scanner and it appears the file name never shows are the result. instead it just say result":""  any tips on how to change this?

**Comment by blacktop** [comment]
You can see how I test the plugin here: https://github.com/malice-plugins/sophos/blob/master/Makefile#L91

How are you trying to scan?

**Comment by CGreen4u** [comment]
Hi,

I seem to be running it similarly but maybe my modification to the dockerfile has disrupted the go code. The only alterations I made was to the OS so it’s still not very clear because the plugin is not based on the Linux operating system.

Chris Green
(314) 517-6924<tel:(314)%20517-6924>

On Feb 24, 2019, at 4:46 PM, blacktop <notifications@github.com<mailto:notifications@github.com>> wrote:


You can see how I test the plugin here: https://github.com/malice-plugins/sophos/blob/master/Makefile#L91

How are you trying to scan?

**Comment by blacktop** [comment]
I apologize, but I do not support modifications to my plugins, I only triage issues with this repo as it is.

I wish you luck.
